# Generated by Django 2.1.5 on 2020-05-04 18:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('provinces', '0002_auto_20200320_1146'),
        ('commerces', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commerceId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='commerces.Commerce')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True)),
                ('firstName', models.CharField(max_length=50)),
                ('lastName', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=50)),
                ('profilePicture', models.URLField(blank=True, max_length=300, null=True)),
                ('softDelete', models.DateTimeField(blank=True, null=True)),
                ('commerceId', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='commerces.Commerce')),
                ('provinceId', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='provinces.Province')),
            ],
        ),
        migrations.AddField(
            model_name='favorite',
            name='profileId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.Profile'),
        ),
    ]
