# Generated by Django 2.1.5 on 2020-05-13 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='ratingCount',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='ratingTotal',
            field=models.IntegerField(default=0),
        ),
    ]
