# Generated by Django 2.1.5 on 2020-03-20 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.RenameField('Profile', 'profileId', 'clientId'),
    ]
