# Generated by Django 2.1.5 on 2020-03-20 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_auto_20200320_1230'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='commerceId',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='provinceId',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
