# Generated by Django 2.1.5 on 2020-03-20 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_auto_20200320_1418'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='profilePicture',
            field=models.URLField(blank=True, max_length=300, null=True),
        ),
    ]
