# Generated by Django 2.1.5 on 2020-03-26 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_auto_20200320_1458'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='clientId',
        ),
        migrations.AlterField(
            model_name='profile',
            name='id',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
    ]
