# Generated by Django 2.1.5 on 2020-03-26 06:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0006_auto_20200326_0330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='commerceId',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='commerces.Commerce'),
        ),
    ]
