# Generated by Django 2.1.5 on 2020-04-30 20:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0009_auto_20200430_1948'),
    ]

    operations = [
        migrations.RenameField(
            model_name='favorite',
            old_name='clientId',
            new_name='profileId',
        ),
    ]
