# Generated by Django 2.1.5 on 2020-04-30 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('areas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='area',
            name='image',
            field=models.URLField(blank=True, max_length=300, null=True),
        ),
    ]
