# Generated by Django 2.1.5 on 2020-04-20 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='court',
            name='price',
            field=models.FloatField(),
        ),
    ]
