# Generated by Django 2.1.5 on 2020-04-30 20:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('commerces', '0005_auto_20200430_2000'),
        ('profiles', '0009_auto_20200430_1948'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inviteDate', models.DateTimeField()),
                ('startDate', models.DateTimeField(blank=True, null=True)),
                ('softDelete', models.DateTimeField(blank=True, null=True)),
                ('commerceId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='commerces.Commerce')),
                ('profileId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.Profile')),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('value', models.SmallIntegerField()),
                ('softDelete', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='employee',
            name='roleId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employees.Role'),
        ),
    ]
