# Generated by Django 2.1.5 on 2020-05-02 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_employee_visible'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='visible',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
