# Generated by Django 2.1.5 on 2020-05-03 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='employeesIds',
            field=models.ManyToManyField(blank=True, null=True, to='employees.Employee'),
        ),
    ]
