# Generated by Django 2.1.5 on 2020-05-13 21:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0002_auto_20200512_2238'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='reservationId',
        ),
        migrations.AddField(
            model_name='reservation',
            name='clientReviewId',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='client_review', to='reservations.Review'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='commerceReviewId',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commerce_review', to='reservations.Review'),
        ),
    ]
