# Generated by Django 2.1.5 on 2020-05-04 18:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('provinces', '0002_auto_20200320_1146'),
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('image', models.URLField(blank=True, max_length=300, null=True)),
                ('softDelete', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Commerce',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('cuit', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('profilePicture', models.URLField(blank=True, max_length=300, null=True)),
                ('headerPicture', models.URLField(blank=True, max_length=300, null=True)),
                ('softDelete', models.DateTimeField(blank=True, null=True)),
                ('areaId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='commerces.Area')),
                ('provinceId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='provinces.Province')),
            ],
        ),
    ]
