# Generated by Django 2.1.5 on 2020-04-30 19:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('commerces', '0002_auto_20200430_1948'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commerce',
            name='areaId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='areas.Area'),
        ),
    ]
