# Generated by Django 2.1.5 on 2020-05-14 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerces', '0002_auto_20200513_2020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commerce',
            name='ratingTotal',
            field=models.FloatField(default=0),
        ),
    ]
