# Generated by Django 2.1.5 on 2020-04-30 20:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('commerces', '0004_auto_20200430_1958'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commerce',
            name='areaId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='areas.Area'),
        ),
    ]
