# Generated by Django 2.1.5 on 2020-04-29 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='reservationMinLength',
            field=models.SmallIntegerField(default=60),
            preserve_default=False,
        ),
    ]
