# Generated by Django 2.1.5 on 2020-04-30 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0002_schedule_reservationminlength'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='startDate',
            field=models.DateTimeField(),
        ),
    ]
