# Generated by Django 2.1.5 on 2020-05-19 17:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('commerces', '0003_auto_20200514_1931'),
        ('employees', '0002_auto_20200504_1854'),
        ('schedules', '0002_auto_20200512_2033'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduleSetting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reservationDayPeriod', models.SmallIntegerField()),
                ('reservationMinCancelTime', models.SmallIntegerField()),
                ('commerceId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='commerces.Commerce')),
                ('employeeId', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='employees.Employee')),
            ],
        ),
    ]
