# Generated by Django 2.1.5 on 2020-05-01 20:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
        ('schedules', '0003_auto_20200430_1650'),
    ]

    operations = [
        migrations.AddField(
            model_name='day',
            name='softDelete',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='schedule',
            name='employeeId',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='employees.Employee'),
        ),
        migrations.AddField(
            model_name='workshift',
            name='softDelete',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
