# Generated by Django 2.1.5 on 2020-05-19 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0004_remove_day_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='Month',
            fields=[
                ('id', models.SmallIntegerField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=20)),
                ('softDelete', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
