# Generated by Django 2.1.5 on 2020-05-14 21:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='notificationTypeId',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='notifications.NotificationType'),
            preserve_default=False,
        ),
    ]
